sqlite3:
  adapter: sqlite3
  database: finder_form_plugin_test.sqlite3
  timeout: 5000

mysql:
  adapter: mysql
  database: finder_form_test
  encoding: utf8
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock
  # connect_timeout: 5000
  read_timeout: 3000
  write_timeout: 5000

postgresql:
  adapter: postgresql
  database: finder_form_test
  encoding: unicode
  host: localhost
  username: postgres
  password: 
